export const SAMPLE_LEADS = [
  {
    id: "LD-001",
    firstName: "John",
    lastName: "Doe",
    companyName: "Acme Corp",
    mobileNumber: "+91 98765 43210",
    alternateMobileNumber: "",
    emailAddress: "john@acme.com",
    whatsappNumber: "+91 98765 43210",
    leadType: "Company",
    preferredContactMethod: "Mobile",
    
    industryType: "Technology",
    gstNumber: "22AAAAA0000A1Z5",
    website: "https://acmecorp.com",
    registrationNumber: "REG12345",
    annualRevenue: "5000000",
    numberOfEmployees: "50",

    serviceRequired: "Commercial Building",
    constructionType: "New Construction",
    estimatedArea: "5000",
    floors: "3",
    budget: "500000",
    expectedStartDate: "2024-06-01",
    projectLocation: "Bangalore",

    doorNo: "123",
    street: "Business Road",
    area: "Tech Park",
    landmark: "",
    city: "Bangalore",
    district: "Bangalore Urban",
    state: "Karnataka",
    pincode: "560001",
    googleMapLocation: "",

    leadSource: "Website",
    sourceDetails: "",
    campaignName: "",
    referredBy: "",

    assignedSalesExecutive: "Sarah Jenkins",
    leadOwner: "Auto",
    leadPriority: "Medium",
    leadStatus: "New",
    expectedClosingDate: "2024-05-15",
    probability: "50",

    additionalInformation: "Call to discuss requirements",
    image: "https://placehold.co/40x40/d1d5db/4b5563?text=JD",
  },
  {
    id: "LD-002",
    firstName: "Priya",
    lastName: "Sharma",
    companyName: "Sharma Builders",
    mobileNumber: "+91 91234 56789",
    alternateMobileNumber: "",
    emailAddress: "priya@sharmabuilders.in",
    whatsappNumber: "+91 91234 56789",
    leadType: "Company",
    preferredContactMethod: "Email",
    
    industryType: "Real Estate",
    gstNumber: "",
    website: "",
    registrationNumber: "",
    annualRevenue: "",
    numberOfEmployees: "",

    serviceRequired: "Apartment",
    constructionType: "Renovation",
    estimatedArea: "2000",
    floors: "1",
    budget: "1250000",
    expectedStartDate: "2024-07-01",
    projectLocation: "Mumbai",

    doorNo: "45",
    street: "Linking Road",
    area: "Bandra",
    landmark: "",
    city: "Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    pincode: "400050",
    googleMapLocation: "",

    leadSource: "Manual",
    sourceDetails: "",
    campaignName: "",
    referredBy: "",

    assignedSalesExecutive: "Raj Patel",
    leadOwner: "Auto",
    leadPriority: "High",
    leadStatus: "Follow-up Pending",
    expectedClosingDate: "2024-05-16",
    probability: "70",

    additionalInformation: "Send brochure",
    image: "https://placehold.co/40x40/d1d5db/4b5563?text=PS",
  }
];

export const SAMPLE_CLIENTS = [
  {
    id: "CLI-001",
    name: "Acme Corp",
    contactPerson: "John Doe",
    gst: "22AAAAA0000A1Z5",
    pan: "AAAAA0000A",
    phone: "+91 98765 43210",
    email: "billing@acme.com",
    address: "123 Business Road, Tech Park, Bangalore 560001",
    activeProjects: 2,
    pendingDues: "₹1,50,000",
    image: "https://placehold.co/40x40/d1d5db/4b5563?text=AC",
  },
  {
    id: "CLI-002",
    name: "Global Builders",
    contactPerson: "Sanjay Singh",
    gst: "27BBBBB1111B2Z6",
    pan: "BBBBB1111B",
    phone: "+91 91234 98765",
    email: "accounts@globalbuilders.in",
    address: "456 Construction Avenue, Mumbai 400001",
    activeProjects: 5,
    pendingDues: "₹5,00,000",
    image: "https://placehold.co/40x40/d1d5db/4b5563?text=GB",
  },
  {
    id: "CLI-003",
    name: "Sunrise Developers",
    contactPerson: "Anjali Desai",
    gst: "33CCCCC2222C3Z7",
    pan: "CCCCC2222C",
    phone: "+91 99887 11223",
    email: "finance@sunrisedev.com",
    address: "789 Skyline Blvd, Chennai 600001",
    activeProjects: 1,
    pendingDues: "₹0",
    image: "https://placehold.co/40x40/d1d5db/4b5563?text=SD",
  }
];
